import React from 'react';

const Footer = () => (
  <footer className="footer">
    Leading traders and businesses choose traders.ninja (c) 2025
    <br />
    <br />
    <small>(this landing site was proudly generated by 'gpt-4o')</small>
  </footer>
);

export default Footer;
