import React from 'react';

const Footer = () => (
  <footer className="footer">
    Leading traders and businesses choose <a href='https://trades.ninja'>trades.ninja</a> (c) 2025
    <br />
    <br />
    <small>(this landing site was proudly generated by 'gpt-4o')</small>
  </footer>
);

export default Footer;
